### ISSUE TITLE
Remove tuple requirement from `getSample`

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/IncrementalInference.jl#1371]
Currently, the return type from `getSample` should be a `<:Tuple`.
The current plan is to update to:
- Priors: return a point on manifold
- Factors: return anything a user wants as long as it matches with the factor definition, (standard is tangent vector).

x-ref https://github.com/JuliaRobotics/RoME.jl/issues/465

It should just be noted that the parametric solve will still require a `getMeasurementParametric` function to be supported.

It will be a breaking change on priors (not sure on factors), so we should aim for v0.25 or v0.26
- v0.25 is maybe better so users can upgrade priors in one go.

**Comment by dehann** [comment]
both priors or relatives getSample should be able to return multiple values.  Don't force prior's getSample functions to only be a point and nothing else.

**Comment by Affie** [comment]
> Don't force prior's getSample functions to only be a point and nothing else.

Maybe I’m missing something, but i don’t think that fits with the current implementation. Factor samples are used directly as is. We will need to implement the algebra then as with relatives but that ends up exactly the same as combining it in getSample.

**Comment by dehann** [comment]
> Priors: return a point on manifold
> Don't force prior's getSample functions to only be a point and nothing else.
> Maybe I’m missing something,

Users should be able to return a `<:Tuple` from any of the `getSample` functions (prior or relative), whenever the user wants to return multiple values from their own `getSample` -- it's not just a requirement for `<:AbstractRelative`.  Its a requirement for all `<:AbstractFactor`.

> Factors: return anything a user wants as long as it matches with the factor definition, (standard is tangent vector).

Factors for me here implies both `<:AbstractRelative` and `<:AbstractPriors` -- think you saying the same thing here, I'm just checking that it applies to all `<:AbstractFactor`.

It will be great if we can remove the "always `<:Tuple`" return value requirement from `<:IIF.getSample` as per #1373 and JuliaRobotics/RoME.jl#499 to simplify the overall `getSample` story.

Discussion at JuliaRobotics/RoME.jl#465 relates to the design decision on `getSample` return values manifold data format.  I still have the mental model that `<:AbstractPrior` will work with 'manifold points' and `<:AbstractRelative` will work with 'manifold tangents' (which should correspond in factor residual functions).  We can figure out how to consolidate that later to more easily indicate to the user tangents or points are expected.  Ultimately, as above, if the user wants to return on a `<:AbstractRelative` manifold points rather than tangents, they should be able to do so, but users should then understand in their residual functions the implications for groups vs Riemannian.

**Comment by dehann** [comment]
updated above
