### ISSUE TITLE
solveTree! stucks in Juno debugger

### ISSUE THREAD

**Issue by andreyzhitnikov** [JuliaRobotics/IncrementalInference.jl#716]
Hi, 
 solveTree!  function always stucks when run in Juno debugger.

**Comment by dehann** [comment]
HI @andreyzhitnikov, it might be due to the size of the computation -- we usually debug lower down calls individually.  Do you perhaps have a short example of whats failing?

**Comment by andreyzhitnikov** [comment]
fg = initfg()
addVariable!(fg, :x0, Pose2)
addFactor!(fg, [:x0], PriorPose2( MvNormal([10; 10; pi/6.0], Matrix(Diagonal([0.1;0.1;0.05].^2)))))
sym = Symbol("l0")
addVariable!(fg, sym, Point2)
 @show isInitialized(fg, sym)
addFactor!(fg,[sym], PriorPoint2(MvNormal([1; 1], Matrix(Diagonal([0.3;0.3].^2)))))
@show getSolverParams(fg)
# ensureAllInitialized!(fg)
getSolverParams(fg).dbg = true
# list vertices in fg
@show ls(fg)

## Solve graph
tree, smt, hist= solveTree!(fg, maxparallel=1)

**Comment by andreyzhitnikov** [comment]
When I run in REPL everything is fine. But in Juno debugger it stucks on 
do intit of x0
![Screenshot from 2020-05-29 17-17-19](https://user-images.githubusercontent.com/20877529/83269835-520bdc80-a1d0-11ea-90a7-085a500381be.png)

**Comment by andreyzhitnikov** [comment]
It works when I'm setting graphinit option to off. 
opt = getSolverParams(fg)
opt.treeinit = true
opt.graphinit = false

**Comment by andreyzhitnikov** [comment]
It happens also if I enter to this function with Debugger.jl. However, when running with REPL everything works fine
![Screenshot from 2020-05-29 22-35-53](https://user-images.githubusercontent.com/20877529/83298389-06235c80-a1fd-11ea-81cb-ecebf1f34f15.png)

**Comment by dehann** [comment]
I think its just loading too much at once and you are seeing the Debugger working its way through slowly.  First thing I'd suggest is to rather try this method on Juno command line:
```julia
Juno.@enter solveTree!(fg)
```
which can be stepped through more easily:
![Screenshot from 2020-05-29 22-10-12](https://user-images.githubusercontent.com/6412556/83317248-39fc8300-a1f9-11ea-9642-2c335b118bb6.png)


Also note, I think you might have misunderstood the use of maxparallel.  I have since change that in #717.  It is used to prevent very dense factor graphs (albeit an artificial constraint).  Multiprocess or threading is done differently, if that is how you understood it...  (apologies for the ambiguity).

A last note (which I will start doing more in the docs is simplified:
```julia
using LinearAlgebra

cov = diagm([0.1;0.1;0.01].^2)
```

**Comment by dehann** [comment]
On this: https://github.com/JuliaRobotics/IncrementalInference.jl/issues/716#issuecomment-636111844

please note that treeinit is experimental and likely won't produce satisfactory results -- you can follow the progress here #602.  Best to use `graphinit` or `initManual!(fg, :x0,...)` interfaces at this time.

**Comment by andreyzhitnikov** [comment]
Thanks!
